import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../src/components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        {/* Sidebar - Fixed on the left */}
        <Sidebar />

        {/* Main Content - Takes up remaining space on the right */}
        <main className="flex-1 p-4 max-w-7xl overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
