import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../src/components/Sidebar";
import Script from 'next/script';
import { Toaster } from "@/components/ui/sonner"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        {/* Sidebar - Fixed on the left */}
        <Sidebar />

        {/* Main Content - Takes up remaining space on the right */}
        <main className="flex-1 p-4 max-w-7xl overflow-y-auto">
          {children}
          <Toaster />
          <Script
          src="https://cdn.qz.io/2.1.7/qz-tray.js"
          strategy="afterInteractive"
        />
        </main>
      </body>
    </html>
  );
}
